version: '3.8'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: database_is_fun01
      MYSQL_DATABASE: test
      MYSQL_USER: data_guru
      MYSQL_PASSWORD: D3rkSt4r_Pa$$w0rd_0xff_3xtreme[1337]
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - vuln_net

  darkstar:
    build:
      context: ./darkstar
      dockerfile: Dockerfile
    container_name: darkstar
    depends_on:
      - mariadb
    networks:
      - vuln_net

volumes:
  mariadb_data:

networks:
  vuln_net:
    driver: bridge
